development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: blog_db
  pool: 5
  username: pguser
  password: postgres
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: demo_test_test
  pool: 5
  username: pguser
  password: postgres
  timeout: 5000
  
production:
  adapter: postgresql
  encoding: utf8
  database: blog_db
  pool: 5
  username: pguser
  password: postgres
  timeout: 5000